---
ReportDefinitions:
- reportName: ESApplicationStatusReport
  summary: Number of Estate brnach applications by their status
  version: 1.0.0
  moduleName: rainmaker-es
  sourceColumns:
  - name: branchType
    label: report.es.branchType
    type: string
    source: estate
    total: false
  - name: status
    label: report.es.status
    type: string
    source: estate
    total: false
  - name: total
    label: report.es.total
    type: string
    source: estate
    total: true
  searchParams:
  - name: fromDate
    label: reports.es.fromDate
    type: epoch
    source: estate
    isMandatory: false
    searchClause: AND application.last_modified_time >= $fromDate 
  - name: toDate
    label: reports.es.toDate
    type: epoch
    source: estate
    isMandatory: false
    searchClause: AND application.last_modified_time <= $toDate
  - name: branchType
    label: report.es.branchType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=branchType|$.MdmsRes.EstateServices.branchType.*.name|$.MdmsRes.EstateServices.branchType.*.name
    source: estate
    wrapper: true
    isMandatory: true
    searchClause: AND application.branch_type=$branchType
  - name: applicationType
    label: report.es.applicationType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=applicationTypes|$.MdmsRes.EstateServices.applicationTypes.*.type|$.MdmsRes.EstateServices.applicationTypes.*.name
    source: estate
    wrapper: true
    isMandatory: false
    searchClause: AND application.application_type = split_part($applicationType,'_',3)
  query: SELECT COUNT(application.application_number) as total,message.message as status,application.branch_type as branchType FROM cs_ep_application_v1 application LEFT OUTER JOIN message ON message.code = application.state AND message.locale = 'en_IN' WHERE application.tenantid LIKE $tenantid AND message.message is not null 
  groupby: GROUP BY message.message,application.branch_type
  
  
- reportName: ESRegistryReport
  summary: Estate Branch Registry Report
  version: 1.0.0
  moduleName: rainmaker-es
  sourceColumns:
  - name: receiptnumber
    label: report.es.receiptnumber
    type: string
    source: eb
    total: false
  - name: receiptIssueDate
    label: report.es.receiptissuedate
    type: string
    source: eb
    total: false
  - name: applicationNumber
    label: report.es.applicationNumber
    type: string
    source: eb
    total: false
  - name: name
    label: report.es.user.name
    type: string
    source: eb
    total: false
  - name: mobileno
    label: report.es.user.mobilenumber
    type: string
    source: eb
    total: false
  - name: transactionnumber
    label: report.es.transactionumber
    type: string
    source: eb
    total: false
  - name: status
    label: report.es.status
    type: string
    source: eb
    total: false
  - name: branchType
    label: report.es.branchType
    type: string
    source: eb
    total: false
  - name: applicationtype
    label: report.es.applicationtype
    type: string
    source: eb
    total: false
  - name: paymenttype
    label: report.es.paymenttype
    type: string
    source: rent
    total: false
  - name: totalamount
    label: report.es.receipt.totalamount
    type: string
    source: eb
    total: true
  searchParams:
  - name: fromDate
    label: reports.es.fromDate
    type: epoch
    source: eb
    isMandatory: false
    searchClause: AND payment.createdtime >= $fromDate
  - name: toDate
    label: reports.es.toDate
    type: epoch
    source: eb
    isMandatory: false
    searchClause: AND payment.createdtime  <= $toDate
  - name: branchType
    label: report.es.branchType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=branchType|$.MdmsRes.EstateServices.branchType.*.name|$.MdmsRes.EstateServices.branchType.*.name
    source: estate
    wrapper: true
    isMandatory: true
    searchClause: AND application.branch_type=$branchType
  - name: applicationType
    label: report.es.applicationType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=applicationTypes|$.MdmsRes.EstateServices.applicationTypes.*.type|$.MdmsRes.EstateServices.applicationTypes.*.name
    source: estate
    wrapper: true
    isMandatory: false
    searchClause: AND application.application_type = split_part($applicationType,'_',3)    
  query: |
    SELECT 
      application.application_number as applicationNumber,
      msg.message as status,
      to_char(To_timestamp(pd.receiptdate / 1000), 'DD/MM/YYYY') as receiptIssueDate , 
      pd.receiptnumber,
      application.branch_type as branchType,
      application.application_type as applicationtype,
      od.owner_name as name,
      od.mobile_number as mobileno,
      payment.transactionnumber as transactionnumber,
      payment.totalamountpaid as totalamount,
      payment.paymentmode as paymenttype
    FROM cs_ep_application_v1 application 
    LEFT OUTER JOIN cs_ep_property_v1 pt ON pt.id = application.property_id 
    LEFT OUTER JOIN cs_ep_property_details_v1 ptd on ptd.property_id = pt.id
    LEFT OUTER JOIN cs_ep_owner_v1 owner on owner.property_details_id = ptd.id
    LEFT OUTER JOIN cs_ep_owner_details_v1 od on od.owner_id = owner.id
    INNER JOIN  message msg ON  msg.code = application.state AND msg.locale = 'en_IN'
    LEFT OUTER JOIN egcl_bill bill ON bill.consumercode = application.application_number 
    LEFT OUTER JOIN egcl_paymentdetail as pd ON pd.billid = bill.id
    LEFT OUTER JOIN egcl_payment as payment ON pd.paymentid = payment.id
    WHERE application.state in ('ES_PENDING_DA_PREPARE_LETTER', 'ES_PENDING_SO_APPROVAL','ES_PENDING_DA_PREPARE_LETTER',
    'ES_PENDING_SO_APPROVAL','ES_PENDING_CITIZEN_NOTICE_DOCUMENTS','ES_PENDING_DS_NOTICE_VERIFICATION','ES_PENDING_NOTICE_CLARIFICATION',
    'ES_PENDING_DA_NOTICE_VERIFICATION','ES_PENDING_SRA_NOTICE_VERIFICATION','ES_PENDING_SO_NOTICE_VERIFICATION', 'ES_APPROVED') 
    AND application.state != 'null' 
    AND application.tenantId LIKE $tenantid
    
    
- reportName: ESCollectionReport
  summary: Estate Branch Collection Report
  version: 1.0.0
  moduleName: rainmaker-es
  sourceColumns:
  - name: applicationtype
    label: report.es.applicationType
    type: string
    source: application
    total: false
  - name: transactionCount
    label: report.es.totalTransaction
    type: string
    source: application
    total: false
  - name: online
    label: report.es.online.collection
    type: string
    source: application
    total: true
  - name: offline
    label: report.es.offline.collection
    type: string
    source: application
    total: true
  - name: total
    label: report.es.totalCollection
    type: string
    source: application
    total: true
  searchParams:
  - name: fromDate
    label: reports.es.fromDate
    type: epoch
    source: application
    isMandatory: false
    searchClause: AND payment.createdtime >= $fromDate
  - name: toDate
    label: reports.es.toDate
    type: epoch
    source: application
    isMandatory: false
    searchClause: AND payment.createdtime <= $toDate
  - name: branchType
    label: report.es.branchType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=branchType|$.MdmsRes.EstateServices.branchType.*.name|$.MdmsRes.EstateServices.branchType.*.name
    source: estate
    wrapper: true
    isMandatory: true
    searchClause: AND application.branch_type=$branchType
  query: |
    SELECT
        COUNT(bill.consumercode) as transactionCount,
        application.application_type as applicationtype,
        SUM(onl.totalamountpaid) as online,
        SUM(offl.totalamountpaid) as offline,
       COALESCE(SUM(onl.totalamountpaid),0)+ COALESCE(SUM(offl.totalamountpaid),0) as total 
    FROM cs_ep_application_v1 application
    LEFT OUTER JOIN egcl_bill bill ON bill.consumercode = application.application_number 
    LEFT OUTER JOIN egcl_paymentdetail as pd ON pd.billid = bill.id
    LEFT OUTER JOIN egcl_payment as payment ON pd.paymentid = payment.id
    LEFT OUTER JOIN (SELECT * FROM egcl_payment WHERE paymentmode = 'ONLINE') AS onl ON  pd.paymentid = onl.id 
    LEFT OUTER JOIN (SELECT * FROM egcl_payment WHERE paymentmode = 'CASH') AS offl ON pd.paymentid = offl.id
    WHERE application.state in ('ES_PENDING_DA_PREPARE_LETTER', 'ES_PENDING_SO_APPROVAL','ES_PENDING_DA_PREPARE_LETTER',
    'ES_PENDING_SO_APPROVAL','ES_PENDING_CITIZEN_NOTICE_DOCUMENTS','ES_PENDING_DS_NOTICE_VERIFICATION','ES_PENDING_NOTICE_CLARIFICATION',
    'ES_PENDING_DA_NOTICE_VERIFICATION','ES_PENDING_SRA_NOTICE_VERIFICATION','ES_PENDING_SO_NOTICE_VERIFICATION', 'ES_APPROVED') AND application.tenantId LIKE $tenantid
  groupby: GROUP BY applicationtype


- reportName: EstateRentRegistryReport
  summary: Estate Rent Registry Report
  version: 1.0.0
  moduleName: rainmaker-es
  sourceColumns:
  - name: receiptnumber
    label: report.es.receiptnumber
    type: string
    source: rent
    total: false
  - name: receiptIssueDate
    label: report.es.receiptissuedate
    type: string
    source: rent
    total: false
  - name: file_number
    label: report.es.filenumber
    type: string
    source: rent
    total: false
  - name: branchType
    label: report.es.branchType
    type: string
    source: rent
    total: false
  - name: name
    label: report.es.user.name
    type: string
    source: rent
    total: false
  - name: mobileno
    label: report.es.user.mobilenumber
    type: string
    source: rent
    total: false
  - name: transactionnumber
    label: report.es.transactionumber
    type: string
    source: rent
    total: false
  - name: paymenttype
    label: report.es.paymenttype
    type: string
    source: rent
    total: false
  - name: totalamount
    label: report.es.receipt.totalamount
    type: string
    source: rent
    total: true
  searchParams:
  - name: fromDate
    label: reports.es.fromDate
    type: epoch
    source: rent
    isMandatory: false
    searchClause: AND payment.createdtime >= $fromDate
  - name: toDate
    label: reports.es.toDate
    type: epoch
    source: rent
    isMandatory: false
    searchClause: AND payment.createdtime  <= $toDate 
  - name: branchType
    label: report.es.branchType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=branchType|$.MdmsRes.EstateServices.branchType.*.code|$.MdmsRes.EstateServices.branchType.*.name
    source: estate
    wrapper: true
    isMandatory: true
    searchClause: AND ptd.branch_type=concat(split_part($branchType,'_',2),'_', split_part($branchType,'_',1))
  - name: file_number
    label: report.es.filenumber
    type: string
    source: rent
    isMandatory: false
    searchClause: AND pt.file_number  = $file_number 
  query: |
    SELECT 
      distinct payment.transactionnumber as transactionnumber,
      pt.file_number,
      CASE WHEN ptd.branch_type = 'ESTATE_BRANCH' THEN 'Estate Branch' WHEN ptd.branch_type = 'BUILDING_BRANCH' THEN 'Building Branch' WHEN ptd.branch_type = 'MANIMAJRA_BRANCH' THEN 'Manimajra Branch' ELSE '' END as branchType,
      to_char(To_timestamp(pd.receiptdate / 1000), 'DD/MM/YYYY') as receiptIssueDate , 
      pd.receiptnumber,
      payment.payername as name,
      payment.mobilenumber as mobileno,
      payment.totalamountpaid as totalamount,
      payment.paymentmode as paymenttype,
      bill.consumercode
    FROM cs_ep_property_v1 pt
    INNER JOIN cs_ep_property_details_v1 ptd on ptd.property_id = pt.id
    LEFT OUTER JOIN egcl_bill bill ON bill.consumercode like concat(FORMAT('SITE-%s',pt.file_number), '%')
    LEFT OUTER JOIN egcl_paymentdetail as pd ON pd.billid = bill.id
    LEFT OUTER JOIN egcl_payment as payment ON pd.paymentid = payment.id 
    WHERE pt.tenantId LIKE $tenantid AND payment.transactionnumber != 'null'

    
- reportName: EstateRentCollectionReport
  summary: Estate Rent Collection Report
  version: 1.0.0
  moduleName: rainmaker-es
  sourceColumns:
  - name: file_number
    label: report.es.fileNumber
    type: string
    source: rent
    total: false
  - name: branchType
    label: report.es.branchType
    type: string
    source: rent
    total: false
  - name: transactionCount
    label: report.es.totalTransaction
    type: string
    source: rent
    total: false
  - name: online
    label: report.es.online.collection
    type: string
    source: rent
    total: true
  - name: offline
    label: report.es.offline.collection
    type: string
    source: rent
    total: true
  - name: total
    label: report.es.totalCollection
    type: string
    source: rent
    total: true
  searchParams:
  - name: fromDate
    label: reports.es.fromDate
    type: epoch
    source: rent
    isMandatory: false
    searchClause: AND payment.createdtime >= $fromDate
  - name: toDate
    label: reports.es.toDate
    type: epoch
    source: rent
    isMandatory: false
    searchClause: AND payment.createdtime <= $toDate
  - name: branchType
    label: report.es.branchType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=branchType|$.MdmsRes.EstateServices.branchType.*.code|$.MdmsRes.EstateServices.branchType.*.name
    source: estate
    wrapper: true
    isMandatory: true
    searchClause: AND ptd.branch_type=concat(split_part($branchType,'_',2),'_', split_part($branchType,'_',1))
  query: |
    SELECT 
      COUNT(bill.consumercode) as transactionCount,
      pt.file_number,
      CASE WHEN ptd.branch_type = 'ESTATE_BRANCH' THEN 'Estate Branch' WHEN ptd.branch_type = 'BUILDING_BRANCH' THEN 'Building Branch' WHEN ptd.branch_type = 'MANIMAJRA_BRANCH' THEN 'Manimajra Branch' ELSE '' END as branchType,
      SUM(onl.totalamountpaid) as online,
      SUM(offl.totalamountpaid) as offline,
      COALESCE(SUM(onl.totalamountpaid),0)+ COALESCE(SUM(offl.totalamountpaid),0) as total
     FROM cs_ep_property_v1 pt
     INNER JOIN cs_ep_property_details_v1 ptd on ptd.property_id = pt.id
     LEFT OUTER JOIN egcl_bill bill ON bill.consumercode like concat(FORMAT('SITE-%s',pt.file_number), '%')
     LEFT OUTER JOIN egcl_paymentdetail as pd ON pd.billid = bill.id
     LEFT OUTER JOIN egcl_payment as payment ON pd.paymentid = payment.id 
     LEFT OUTER JOIN (SELECT * FROM egcl_payment WHERE paymentmode = 'ONLINE') AS onl ON  pd.paymentid = onl.id 
     LEFT OUTER JOIN (SELECT * FROM egcl_payment WHERE paymentmode = 'CASH') AS offl ON pd.paymentid = offl.id
     WHERE pt.tenantId LIKE $tenantid AND payment.transactionnumber != 'null' 
  groupby: GROUP BY  pt.file_number,ptd.branch_type
  
- reportName: EstateRentDueReport
  summary: Estate Due Amount Report
  version: 1.0.0
  moduleName: rainmaker-es
  sourceColumns:
  - name: file_number
    label: report.es.filenumber
    type: string
    source: due
    total: false
  - name: branchType
    label: report.es.branchType
    type: string
    source: due
    total: false
  - name: property_type
    label: report.es.propertyType
    type: string
    source: due
    total: false
  - name: sectorNumber
    label: report.es.sectorNumber
    type: string
    source: due
    total: false
  - name: owner_name
    label: report.es.owner.name
    type: string
    source: due
    total: false
  - name: mobile_number
    label: report.es.user.mobilenumber
    type: string
    source: due
    total: false
  - name: balance_rent
    label: report.es.balanceRent
    type: string
    source: due
    total: true
  - name: balance_rent_penalty
    label: report.es.balanceRentPenalty
    type: string
    source: due
    total: true
  - name: balance_gst
    label: report.es.balanceGST
    type: string
    source: due
    total: true
  - name: balance_gst_penalty
    label: report.es.balanceGSTPenalty
    type: string
    source: due
    total: true
  - name: balance_interest
    label: report.es.balanceInterest
    type: string
    source: due
    total: true 
  - name: total_due
    label: report.es.totaldue
    type: string
    source: due
    total: true
  - name: balance_amount
    label: report.es.balanceamount
    type: string
    source: due
    total: true
   
  searchParams:
  - name: branchType
    label: report.es.branchType
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=branchType|$.MdmsRes.EstateServices.branchType.*.code|$.MdmsRes.EstateServices.branchType.*.name
    source: estate
    wrapper: true
    isMandatory: true
    searchClause: AND due.branch_type=concat(split_part($branchType,'_',2),'_', split_part($branchType,'_',1))
  - name: sector
    label: report.es.sector
    type: singlevaluelist
    pattern: http://localhost:8094/egov-mdms-service/v1/_get?tenantId=ch&moduleName=EstateServices&masterName=sector|$.MdmsRes.EstateServices.sector.*.name|$.MdmsRes.EstateServices.sector.*.name
    source: due
    wrapper: true
    isMandatory: false
    searchClause: AND due.sector = $sector
  query: |
    SELECT 
      file_number,
      CASE WHEN branch_type = 'ESTATE_BRANCH' THEN 'Estate Branch' WHEN branch_type = 'BUILDING_BRANCH' THEN 'Building Branch' WHEN branch_type = 'MANIMAJRA_BRANCH' THEN 'Manimajra Branch' ELSE '' END as branchType,
      property_type,
      sectorNumber,
      owner_name,
      mobile_number,
      balance_rent,
      balance_rent_penalty,
      balance_gst,
      balance_gst_penalty,
      balance_interest,
      rent,
      gst,
      rent_penalty,
      gst_penalty,
      COALESCE(SUM(balance_rent),0)+ COALESCE(SUM(balance_rent_penalty),0) + COALESCE(SUM(balance_gst),0)+ COALESCE(SUM(balance_gst_penalty),0)+ COALESCE(SUM(balance_interest),0) as total_due,
      balance_amount 
    FROM cs_ep_dueamount due
    WHERE due.tenantId LIKE $tenantid
  groupby: GROUP BY file_number,branch_type,property_type,sectorNumber,owner_name,mobile_number,balance_rent,balance_rent_penalty,balance_gst,balance_gst_penalty,balance_interest,rent,gst,rent_penalty,gst_penalty,balance_amount 


